name: Print Message on Deployment

# Trigger on deployment
on:
  push:
    branches:
      - main  # Make sure your push is going to `main`

  deployment_status:
    types: [success]

jobs:
  print-message:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Print the message
      - name: Print deployment message
        run: |
          echo "this string is printed on deployment"
        shell: bash # By default, bash works across Linux and macOS
        
      
