name: Post Deployment Check Validation

run-name: Validate Workflow for ${{ github.event.workflow_run.head_commit.message }}

on:
  workflow_run:
    workflows: ["Deploy workflow"]
    types:
      - completed

  # Adding `workflow_dispatch` to allow manual inputs again
  workflow_dispatch:
    inputs:
      environment:
        description: environment
        default: env1
        required: true
        type: choice
        options:
          - env1
          - env2
          - env3
          - env4
          - env5
          - env6
          - env7
          - env8
          - env9
          - env10
      project:
        description: the “___” project directory containing the job
        required: true
      deploy_job:
        description: job name
        required: true

jobs:
  validate:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch outputs from deploy workflow
        id: fetch_outputs
        uses: actions/github-script@v6
        with:
          script: |
            const runId = ${{ github.event.workflow_run.id }};
            const owner = context.repo.owner;
            const repo = context.repo.repo;

            const workflowRun = await github.rest.actions.getWorkflowRun({
              owner,
              repo,
              run_id: runId
            });

            const deployJob = workflowRun.data.outputs.deploy_job;
            const project = workflowRun.data.outputs.project;

            core.exportVariable('DEPLOY_JOB', deployJob);
            core.exportVariable('PROJECT', project);
            return { deployJob, project };

            
      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0
          
    
      # - name: Post-deployment validation message
      #   run: |
      #     echo "Validating deployment of job: ${{ env.DEPLOY_JOB }} from project: ${{ env.PROJECT }}"
      #   shell: bash
